### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by ddkwork** [tarunKoyalwar/Sandman#1]
Can you make a table container with additem method. Sort row,copy rows title etc,like charles ui.

**Comment by tarunKoyalwar** [comment]
Can you describe it more maybe with screenshot and where do you want a table container . 

I actually completed all todo of this project .Since fyne is not that developed yet . I intend to create  a new project entirely with flutter and go .

**Comment by ddkwork** [comment]
> Can you describe it more maybe with screenshot and where do you want a table container .
> 
> I actually completed all todo of this project .Since fyne is not that developed yet . I intend to create a new project entirely with flutter and go .

https://www.charlesproxy.com/

https://images.sftcdn.net/images/t_app-cover-l,f_auto/p/2c8ecad8-96d7-11e6-a1be-00163ec9f5fa/3576983848/charles-screenshot.png

**Comment by tarunKoyalwar** [comment]
@ddkwork ,  I can make it but what type of data is it intended to store

**Comment by ddkwork** [comment]
> @ddkwork ,  I can make it but what type of data is it intended to store

Binary

**Comment by ddkwork** [comment]
> @ddkwork ,  I can make it but what type of data is it intended to store

Can you release it for study?
